--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1
-- Dumped by pg_dump version 16.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: player; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.player (
    player_id bigint NOT NULL,
    first_name character varying(80) NOT NULL,
    last_name character varying(80) NOT NULL,
    "position" character varying(2) NOT NULL,
    player_number integer NOT NULL,
    height integer DEFAULT 66,
    weight integer DEFAULT 180
);


ALTER TABLE public.player OWNER TO postgres;

--
-- Name: COLUMN player.height; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.player.height IS 'Player''s height in inches';


--
-- Name: COLUMN player.weight; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.player.weight IS 'Player''s weight in pounds';


--
-- Name: player_player_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.player ALTER COLUMN player_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.player_player_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: player; Type: TABLE DATA; Schema: public; Owner: postgres
-- These are simply test values, this section can be omitted if you wish to start with a clean database
--

COPY public.player (player_id, first_name, last_name, "position", player_number, height, weight) FROM stdin;
1	John	Doe	QB	1	72	190
3	John	Smith	RB	2	100	100
4	Jane	Johnson	TE	44	100	200
\.


--
-- Name: player_player_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.player_player_id_seq', 5, true);


--
-- Name: player player_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.player
    ADD CONSTRAINT player_pkey PRIMARY KEY (player_id);


--
-- PostgreSQL database dump complete
--

